# Generated by Django 4.2.7 on 2023-11-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='boy.jpg', null=True, upload_to='Profile_Images'),
        ),
    ]
