# Generated by Django 4.2.7 on 2023-11-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_image'),
        ('user', '0004_alter_customuser_username_alter_profile_staff'),
    ]

    operations = [
    ]
