# Generated by Django 4.2.7 on 2023-11-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Stationary', 'Stationary'), ('Others', 'Others')], max_length=30, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
