# Generated by Django 4.2.7 on 2023-11-19 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name_plural': 'Quantity'},
        ),
    ]
