# Generated by Django 4.2.7 on 2023-11-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_item_options_alter_quantity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name_plural': 'Item Details'},
        ),
        migrations.AddField(
            model_name='quantity',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Stationary', 'Stationary'), ('Others', 'Others')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='quantity',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
