# Generated by Django 4.2.7 on 2023-11-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_quantity_options_quantity_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
